# Generated by Django 5.2.7 on 2025-10-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_seller_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
