# Generated by Django 5.2.7 on 2025-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_book_genre_book_published_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('instructor', models.CharField(max_length=100)),
                ('category', models.CharField(default='General', max_length=100)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(default='Drama', max_length=50)),
                ('release_year', models.IntegerField(default=2024)),
                ('rating', models.FloatField(default=5.0)),
                ('duration', models.IntegerField(default=120)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
